# Generated by Django 6.0 on 2025-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wine_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
